### ISSUE TITLE
How to disable dark mode?

### ISSUE THREAD

**Issue by puneetv05** [maizzle/starter-postmark#20]
Hey @cossssmin thanks for the amazing template 👍🏼 
btw how to disable dark mode ?

**Comment by cossssmin** [comment]
Hi, simply remove the `@screen dark` section in `src/assets/css/custom/postmark/index.css`:

https://github.com/maizzle/starter-postmark/blob/2afe8cc9efdf97dec829bf10b45f9a49d37ddb6f/src/assets/css/custom/postmark/index.css#L32-L61

**Comment by puneetv05** [comment]
thanks @cossssmin !
