### ISSUE TITLE
Not working with maizzle v1.0.0

### ISSUE THREAD

**Issue by mikevosje** [maizzle/starter-postmark#6]
Package.json gives latest as version, that's 1.0.0, but then it's not working:
```
Error: no files with the .html extension found in your `templates.root` path
```
Creating the theme (twice) running this steps:
- `maizzle new`
- provide github repo url https://github.com/maizzle/starter-postmark.git
- install npm repositories: YES

After install: `maizzle serve`.
In the local_build, there are also .njk files, no html files.

Downgrading to 0.7.4 (the one that is provided in de starter-litmus theme) works.
This is also for the mailbakery theme.

See screenshot:
<img width="826" alt="Schermafbeelding 2020-04-28 om 21 47 02" src="https://user-images.githubusercontent.com/3897623/80530889-f9abaa00-8999-11ea-9fa1-ef6f38f38ade.png">

**Comment by cossssmin** [comment]
Yup, none of the starters work with v1.0.0 right now (except maizzle/maizzle). I’ll be updating them one by one, will start with the simpler ones first (like this one and the amp one).

**Comment by cossssmin** [comment]
While I go through them, note that currently all starters work with `0.9.1` (last version before `1.0.0`).

Also, there is [starter-nunjucks](https://github.com/maizzle/starter-nunjucks) for anyone who cannot update to `1.0.0`, but all other starters will be updated and will only work with `1.0.0` and up.

**Comment by cossssmin** [comment]
I've updated the Starter to work with Maizzle v1.x, give it a try and let me know how it goes.
